chunked_download.py: Handle 416 range issue
- If we get a 416, it's likely because it's the first chunk and we're
  using the default chunk size since we don't have the file-size yet.
  If this is the case, just set the total and try.

- If the file-content has already been received at this point, likely
  because it's an empty file, since, at this point, we've received no
  data, just return and report 100% progress.

- This seems to always happen with new files, suddenly. Might have to
  do with the deprecation of the V2 interface.

Traceback (most recent call last):
  File "/home/local/MAGICLEAP/doprea/development/python/gdrivefs/gdrivefs/gdfuse.py", line 391, in create
    mime_type)
  File "/home/local/MAGICLEAP/doprea/development/python/gdrivefs/gdrivefs/opened_file.py", line 224, in __init__
    self.__load_base_from_remote()
  File "/home/local/MAGICLEAP/doprea/development/python/gdrivefs/gdrivefs/opened_file.py", line 311, in __load_base_from_remote
    self.mime_type)
  File "/home/local/MAGICLEAP/doprea/development/python/gdrivefs/gdrivefs/drive.py", line 65, in wrapper
    return f(*args, **kwargs)
  File "/home/local/MAGICLEAP/doprea/development/python/gdrivefs/gdrivefs/drive.py", line 482, in download_to_local
    status, done, total_size = downloader.next_chunk()
  File "/home/local/MAGICLEAP/doprea/.virtualenvs/gdrivefs/lib/python3.5/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/local/MAGICLEAP/doprea/development/python/gdrivefs/gdrivefs/chunked_download.py", line 190, in next_chunk
    raise apiclient.errors.HttpError(resp, content, uri=self._uri)
googleapiclient.errors.HttpError: <HttpError 416 when requesting https://www.googleapis.com/drive/v2/files/1HAj5_CJf45_2O-EsdEZSDPI-t5ad6nle?alt=media&source=downloadUrl returned "Request range not satisfiable">
2020-05-14 07:42:13,905 [gdrivefs.fsutility ERROR] FUSE error [FuseOSError] (5) will be forwarded back to GDFS from [create]: [Errno 5] Input/output error
2020-05-14 07:42:13,905 [gdrivefs.fsutility DEBUG] <<<<<<<<<< create(8) (6834)